### ISSUE TITLE
 MakingDevelopers/src/components/Blog/index.js

### ISSUE THREAD

**Issue by C0rporeus** [MilkZoft/MakingDevelopers#25]
en la parte de los html embebidos en los index, no deberia ir adicional comillas invertidas?

algo asi como esto:

`render() {
    const { __ } = this.props;

```
return (`
  <div>
    <Helmet title={__.Site.title} />

    <h1>I'm React Blog! - {__.Site.language}</h1>
  </div>
`);
```

  }
}`

// Interpolate variable bindings
var name = "Bob", time = "today";
`Hello ${name}, how are you ${time}?`

https://babeljs.io/docs/learn-es2015/

**Comment by csantany** [comment]
No es necesario, puesto que lo interpreta como JSX, los acentos (o comillas invertidas), se usan por ejemplo si quisieras concatenar cosas, digamos:

```javascript
<h1>{`I'm React Blog! - ${__.Site.language}`}</h1>
```

Saludos.

**Comment by C0rporeus** [comment]
A ok, apenas estoy viendo este tema de react, gracias por la aclaración...
