### ISSUE TITLE
Por que abandonaron el proyecto?

### ISSUE THREAD

**Issue by C0rporeus** [MilkZoft/MakingDevelopers#7]
La verdad me a gustado mucho lo que e visto, la forma de interpretar y analizar codigo, la estructura y el uso de ciertas herramientas, aun asi no a comenzado el proyecto en si y veo que durante julio y agosto le trabajaron mucho, no obstante desde agosto noto abandonado el proyecto.

Animo que muchos noobs estamos a la expectativa con ello.

**Comment by csantany** [comment]
Hola @C0rporeus muchas gracias por tu comentario :), el proyecto se había parado justamente por la falta de participación de la gente, pensamos que no les estaba interesando el curso, pero ahora que haces este comentario veo que estaba equivocado, espero continuar con el próximo video al final de esta semana, saludos cordiales!

**Comment by kattsushi** [comment]
sip, estaba siguiendo muy de cerca estos videos! ánimos buen trabajo

**Comment by csantany** [comment]
Ayer volví a retomar el proyecto e hice merge de los nuevos cambios, hoy por la noche explicaré este nuevo código, pero por mientras ya pueden darle un vistazo en la rama `develop`.

**Comment by csantany** [comment]
Ya liberé el nuevo vídeo #11 :) [](https://www.youtube.com/watch?v=d0k49CseyfA)

**Comment by C0rporeus** [comment]
gracias, ya los observe :) animos y muchos exitos
